[package]
name = "sphinx-interpreter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[[bin]]
name = "repl"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0"
lazy_static = "1.4"
string-interner = "0.14"
# rustc-hash = "1.1.0"
ahash = "0.7.6"
log = "0.4.0"
env_logger = "0.8.4"